name: Azure Terraform CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "modules/**"
      - ".github/workflows/ci.yml"
      - ".pre-commit-config.yaml"

jobs:
  pre-commit:
    name: Pre-commit Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run pre-commit on Azure files
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --files modules/**/*.tf

  terraform:
    name: Validate Azure Terraform
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.4.2"

      - name: Terraform Initialization
        uses: hashicorp/terraform-github-actions@v2
        with:
          command: init
          path: modules/azure
          arguments: -backend=false

      - name: Terraform Validation
        uses: hashicorp/terraform-github-actions@v2
        with:
          command: validate
          path: modules/azure

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: modules/azure
          config_file: checkov.yaml
          soft_fail: true
