name: Azure Terraform CD

on:
  push:
    branches:
      - main
    paths:
      - "modules/**"
      - ".github/workflows/cd.yml"

permissions:
  contents: write
  actions: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semantic versioning
        id: versioning
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.versioning.outputs.new_tag }}
          name: Release ${{ steps.versioning.outputs.new_tag }}
          body: ${{ steps.versioning.outputs.changelog }}
          makeLatest: true
          draft: false

      - name: Trigger documentation workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: docs.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{"version": "${{ steps.versioning.outputs.new_tag }}", "changelog": "${{ name: Azure Terraform CD
on:
  push:
    branches:
      - main
    paths:
      - "modules/**"
      - ".github/workflows/cd.yml"
permissions:
  contents: write
  actions: write
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semantic versioning
        id: versioning
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.versioning.outputs.new_tag }}
          name: Release ${{ steps.versioning.outputs.new_tag }}
          body: ${{ steps.versioning.outputs.changelog }}
          makeLatest: true
          draft: false
      - name: Trigger documentation workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: docs.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{"version": "${{ steps.versioning.outputs.new_tag }}", "changelog": ${{ toJSON(steps.versioning.outputs.changelog) }}"}'
