name: Azure Terraform CD

on:
  push:
    branches:
      - main
    paths:
      - "modules/**"
      - ".github/workflows/cd.yml"

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth:

      - name: Semantic versioning
        id: versioning
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.versioning.outputs.new_tag }}
          name: Release ${{ steps.versioning.outputs.new_tag }}
          body: ${{ steps.versioning.outputs.changelog }}
          makeLatest: true
          draft: false

  update-docs:
    name: Update Module Documentation
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest version
        id: latest_version
        uses: pozetroninc/github-action-get-latest-release@v0.6.0
        with:
          repository: ${{ github.repository }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.4.2"

      - name: Update terraform-docs
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: modules
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-commit-message: "docs: Update module documentation for ${{ steps.latest_version.outputs.release }}"
