name: Azure Terraform CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "modules/**"
      - ".github/workflows/ci.yml"
      - ".pre-commit-config.yaml"

permissions:
  contents: read
  pull-requests: read

jobs:
  check-skip:
    name: Check if CI should be skipped
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.skip-check.outputs.skip }}
    steps:
      - name: Skip CI Check
        uses: saulmaldonado/skip-workflow@v1
        id: skip-check
        with:
          phrase: '[skip ci]'
          github-token: ${{ secrets.GITHUB_TOKEN }}

  validate:
    name: Validate Terraform
    needs: check-skip
    if: ${{ needs.check-skip.outputs.skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.4.2"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive modules/

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: Run TFLint
        run: tflint --init
        working-directory: modules

  security:
    name: Security Scan
    needs: [check-skip, validate]
    if: ${{ needs.check-skip.outputs.skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: modules
          framework: terraform
          soft_fail: true
