name: Azure Terraform CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "modules/**"
      - ".github/workflows/ci.yml"
      - ".pre-commit-config.yaml"

permissions:
  contents: read
  pull-requests: read

jobs:
  pre-commit:
    name: Pre-commit Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.4.2"

      - name: Install terraform-docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          git-push: "false"
          working-dir: .
          output-file: README.md
          output-method: inject

      - name: Install tflint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --files modules/**/*.tf

  terraform:
    name: Validate Azure Terraform
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.4.2"

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: modules
          config_file: checkov.yaml
          soft_fail: true
